services:
  server:
    build: .
    container_name: umbrel-encrypted-folder_server_1
    restart: always
    stop_grace_period: 2m
    ports:
      - "3009:3000"
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./data:/data:rshared
