services:
  server:
    build: .
    container_name: umbrel-encrypted-folder_server_1
    restart: always
    stop_grace_period: 2m
    ports:
      - "3009:3000"
    environment:
      MOUNTS_DIR: /umbrel-home/Encrypted Folder/Unlocked
      FILE_BROWSER_MOUNTS_PATH: /Home/Encrypted Folder/Unlocked
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./data:/data:rshared
      - ${UMBREL_ROOT}/home:/umbrel-home:rshared
